#
# Configuration file for the topsecret application.
#
# This file will be sought in the following locations:
#
# * ../nbproject/private/topsecret.yml
# * ~/.topsecret.yml
# * /etc/topsecret.yml
# * ./topsecret.yml
#

development:
  auth:
    # Set to true to ignore authentication credentials, which
    # allows anyone to log in; useful for testing and development.
    fake: true
  ldap:
    host: localhost
    port: 389
    format: 'uid=#{name},ou=people,dc=example,dc=com'

test:
  auth:
    fake: true
  ldap:
    host: localhost
    port: 389
    format: 'uid=#{name},ou=people,dc=example,dc=com'

production:
  auth:
    fake: false
  ldap:
    host: localhost
    port: 389
    format: 'uid=#{name},ou=people,dc=example,dc=com'
