# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "categories", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "user_id",    :string
  end

  create_table "old_passwords", :force => true do |t|
    t.column "password",   :string
    t.column "record_id",  :integer
    t.column "created_at", :datetime
  end

  create_table "records", :force => true do |t|
    t.column "system_name", :string
    t.column "username",    :string
    t.column "password",    :string
    t.column "category_id", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "url",         :string
    t.column "user_id",     :string
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
  end

end
